name: moodexample
description: 管理自己的情绪，记录当下所见所想。
publish_to: 'none'
version: 1.9.11+491

environment:
  sdk: 3.10.0
  flutter: 3.38.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # l10n
    sdk: flutter
  intl: 0.20.2 # i18n/l10n 处理
  path: 1.9.1
  path_provider: 2.1.5 # 路径
  provider: 6.1.5+1 # 状态管理
  sqflite: 2.4.2 # 数据库
  shared_preferences: 2.5.3 # 共享存储
  go_router: 17.0.0 # 路由管理
  flutter_zoom_drawer: 3.2.0 # 缩放抽屉
  flutter_smart_dialog: 4.9.8+9 # Dialog
  table_calendar: 3.2.0 # 日历
  flutter_slidable: 4.0.3 # 滑动操作项
  card_swiper: 3.0.1 # 轮播
  fl_chart: 1.1.1 # 图表
  excel: 4.0.6 # Excel
  share_plus: 12.0.1 # 分享
  file_picker: 10.3.6 # 文件选择
  webview_flutter: 4.13.0 # WebView
  ditredi: 2.0.2 # 3D 数据集显示
  vector_math: 2.2.0
  awesome_notifications: 0.10.1 # 本地通知
  bonfire: 3.16.1 # 游戏引擎相关
  flame: 1.32.0 # 游戏引擎相关
  flutter_screen_lock: 9.2.2+2 # 密码锁
  local_auth: 3.0.0 # 本地认证
  local_auth_android: 2.0.0 # 本地认证
  local_auth_darwin: 2.0.0 # 本地认证
  flutter_tilt: 3.3.2 # 倾斜视差
  remixicon: 1.4.1 # Remixicon

# https://dart.dev/tools/pub/dependencies#dependency-overrides
dependency_overrides:

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: any

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/onboarding/
    - assets/images/woolly/
    - assets/3d/city/
    - assets/images/game/mini_fantasy/
    - assets/images/game/mini_fantasy/tiles/
    - assets/images/game/mini_game/
    - assets/images/game/mini_game/tiles/
    - assets/images/game/mini_game/enemy/orc/
    - assets/images/game/mini_game/enemy/boss/
    - assets/images/game/mini_game/player/human/
